TITLE FIRST TRIAL PROGRAM
DATA SEGMENT
        NO DB 10
DATA ENDS
CODE SEGMENT
        ASSUME CS:CODE,DS:DATA
START:  MOV AX,DATA
        MOV DS,AX
        MOV AX,05
        MOV BL,02
        DIV BL
        MOV AX,4C00H
        INT 21H
CODE ENDS
        END START

